---
name: setup-erlang-otp
description: |
  Set up a specific version of Erlang in your Github Actions workflow
  (optionally with rebar3).
author: Erlangsters
branding:
  color: purple
  icon: code
inputs:
  erlang-version:
    description: Version of Erlang/OTP to set up.
  install-rebar3:
    description: Whether to install rebar3 script.
    default: false
outputs:
  erlang-version:
    description: Erlang/OTP version that was installed.
  erlang-location:
    description: The absolute path of the Erlang/OTP installation location.
  unsupported-musl:
    description: Set to true when install is refused because of musl 1.2.6.
runs:
  using: node20
  main: setup-erlang.js
